### PR TITLE
Minor fixes.

### PR DESCRIPTION
**Pull request by DmRomantsov**

### CODE REVIEW

**Comment by nitinsurana** [comment]
Many changes are specialization, removing the original generalize nature of the project. I'm unsure as to why these changes are required and if still required, how merging them into the project is going to benefit others ?

**Comment by nitinsurana** [comment]
Also, why do we need BitcoindException ? If needed, shouldn't it be named more generic like "RPCException" or similar.

**Comment by DmRomantsov** [comment]
There's no specialized changes, but bug-fixes and cleaning.

I rename it, if it's important for you.

**Comment by DmRomantsov** [comment]
The changes will help to parse the type of transaction, to catch exceptions and write logs. All of this is part of the necessary functionality for convenient work with RPC.

**Comment by DmRomantsov** [comment]
Still relevant.

**Comment by nitinsurana** [comment]
Please update the README on how to use it and what are the exceptions thrown and any other new features.

**Pull request merged**
